FISH-7073 Reapply Payara Enterprise Branding
payara/patched-src-glassfish-woodstock pull request #3
Opened 2023-02-23 14:17 UTC by JamesHillyard

Updates to 5.0.0.payara-p2 and includes a Payara Enterprise profile (enterprise) which will create a woodstock-webui-jsf-suntheme with the `enterprise` classifier.

2023-02-23 14:24 UTC, JamesHillyard commented
@Pandrex247 I don't have permission to request reviewers or merge this PR, could you please review and if all looks good merge it?

2023-02-23 16:44 UTC, Pandrex247 commented
You should now be able to ask for reviewers

2023-02-23 16:45 UTC, Pandrex247 requested changes
Doesn't seem to build when using `enterprise` profile

2023-02-24 09:34 UTC, Pandrex247 approved these changes
We can fix the failing build (and/or look at rejigging how this builds) in another PR.

LGTM

2023-02-27 09:17 UTC, merged